# -*- coding: utf-8 -*-
"""Week2-Work Done.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GkzihQJTJxbzXbP3iyKhkkxdgNcEoTCj

Arithmetic Operators
"""

x = int(input("Enter first number"))
y = int(input("Enter second number"))

print('x + y =',x+y)

print('x - y =',x-y)

print('x * y =',x*y)

print('x / y =',x/y)

print('x // y =',x//y)

print('x ** y =',x**y)

"""Assignment Operator"""

x=int(input("Enter the number"))
x+= 5
print("x += 5""\t",x)
x = x + 5
print("x + 5""\t",x)
x -= 5  
print("x -= 5""\t",x)
x *= 5  
print("x *= 5""\t",x)
x /= 5  
print("x /= 5""\t",x)
x %= 5  
print("x %= 5""\t",x)
x //= 5 
print("x //= 5""\t",x)
x **= 5 
print("x **= 5""\t",x)

"""Logical Operator"""

a = True
b = False

print('a and b is',a and b)

print('a or b is',a or b)

print('not b is',not b)

"""Identity Operators"""

x = 10
y = 10
a = 'Shivam'
b = 'Hello'
c = [1,2,3]
d = [1,2,3]

print(x1 is not y1)

print(x2 is y2)

print(x3 is not y3)

"""For Loop"""

numbers = [8,10,6,9,11,7,3,5]
total = 0
for val in numbers:
    total = total+val

print("The Total Value is", total)

"""range"""

print(range(15))

print(list(range(10)))

print(list(range(2, 9)))

print(list(range(5, 10, 3)))

"""While Loop"""

n = 10
total = 0
s = 1

while s <= n:
    total = total + s
    s = s+1 
print("The Total is", total)

"""Nested If-Else"""

num = float(input("Number is positive: "))
if num >= 0:
    if num == 0:
        print("Number is 0")
    else:
        print("Number is Positive")
else:
    print("Number is Negative")

"""Membership Operator"""

x = 'Sanjivani'
y = {1:'S',2:'a'}

print('M' in x)

print('Sanjivani' not in x)

print(1 in y)

print('a' in y)

"""Pass Statement"""

for ele in 'Sanjivani':
  if ele =="s":
    pass
  print(ele)

"""Continue Statement"""

for ele in 'Sanjivani':
  if ele =="a":
    continue
  print(ele)

"""Break Statement"""

for ele in 'Sanjivani':
  if ele =="v":
    break
  print(ele)